### ISSUE TITLE
Integer overflow in ZlibOutputBuffer causes crash

### ISSUE THREAD

**Issue by jtotzid** [openxla/xla#11668]
In https://github.com/openxla/xla/blob/main/third_party/tsl/tsl/lib/io/zlib_outputbuffer.cc#L158 we are truncating a 64-bit size to 32-bit and comparing it to a threshold.

When the size of input `data` is too big it will wrap around and the check will pass: the truncated size is smaller than the available space (when it actually is not). This will then cause a crash at https://github.com/openxla/xla/blob/main/third_party/tsl/tsl/lib/io/zlib_outputbuffer.cc#L77.

May I suggest instead the integer cast to be:
```
if (bytes_to_write <= static_cast<size_t>(AvailableInputSpace())) {
```
i.e. you are casting to a larger, not a smaller, type.

**Comment by cheshire** [comment]
Thanks ! Could you provide a test case?

**Comment by akuegel** [comment]
I have fixed it in the way you suggested (https://github.com/openxla/xla/commit/2abc3fd2aab39733f2777af5d3c9e1efdd4d7ed5). Please let me know whether it works now as expected.

**Comment by jtotzid** [comment]
thanks for the quick fix!
trying to build from source but encountering some hiccups...

**Comment by penumallas1261** [comment]
Hi @jtotzid ,

Could you please check is this issue fixed if not fixed, To help us investigate, please share the steps you performed and simple standalone code snippet to reproduce the problem.

**Comment by penumallas1261** [comment]
Hi @jtotzid ,

Closing the issue due to inactivity for over 3 months, Please feel free to reopen the issue if you still have a concern. Thanks!
