### ISSUE TITLE
XLA from openxla/xla cannot be built as an bazel subrepository

### ISSUE THREAD

**Issue by hawkinsp** [openxla/xla#793]
I'm attempting to switch JAX to use the openxla/xla copy of XLA, but unfortunately it appears that repository cannot be built as a Bazel submodule, unlike the copy in the TensorFlow repository:

Simple repro:
```
$ git clone https://github.com/openxla/xla.git /tmp/xla
$ cd /tmp/xla && git checkout test
$ cd /tmp
$ mkdir myrepo && cd myrepo
$ cat > WORKSPACE <<EOF
local_repository(
   name = "org_tensorflow",
   path = "/tmp/xla",
)

load("@org_tensorflow//:workspace3.bzl", "tf_workspace3")
tf_workspace3()

load("@org_tensorflow//:workspace2.bzl", "tf_workspace2")
tf_workspace2()

load("@org_tensorflow//:workspace1.bzl", "tf_workspace1")
tf_workspace1()

load("@org_tensorflow//:workspace0.bzl", "tf_workspace0")
tf_workspace0()

EOF

$ touch BUILD
$ bazel build --experimental_repo_remote_exec @org_tensorflow//xla:util

ERROR: Error computing the main repository mapping: at /.../68526d8af9166f1b3b7478289d0f17d6/external/org_tensorflow/workspace2.bzl:14:6: Label '//tools/toolchains/embedded/arm-linux:arm_linux_toolchain_configure.bzl' is invalid because 'tools/toolchains/embedded/arm-linux' is not a package; perhaps you meant to put the colon here: '//:tools/toolchains/embedded/arm-linux/arm_linux_toolchain_configure.bzl'?
```

There are at least two things going wrong.
* references like
```
load("@//tools/toolchains:cpus/aarch64/aarch64_compiler_configure.bzl", "aarch64_compiler_configure")
```
refer to the enclosing repository because of the leading `@`. But there is no such file in the enclosing repository: we want to get these from the XLA repository.

* If we fix the first problem, then we next hit:
```
ERROR: ... :: Error ...: no such package '@tsl//tsl': The repository's path is "third_party/tsl" (absolute: "/.../myrepo/third_party/tsl") but it does not exist or is not a directory.
```

This is because workspace2.bzl uses `local_repository` to create a `@tsl` repository, but `local_repository` per the Bazel documentation requires "This must be a path to the directory containing the repository's WORKSPACE file. The path can be either absolute or relative to the main repository's WORKSPACE file.". That won't work if XLA is itself a submodule.

Please fix? This blocks using the OpenXLA repository from JAX.

**Comment by MichaelHudgins** [comment]
@jakeharmon8 I believe this is encapsulated in the work you are doing but could you update. (Looks like i cant assign this until you join the org)

**Comment by jakeharmon8** [comment]
Should be working now. Just need to pass the path to xla into workspace2:

```
xla_path = "/tmp/xla"
local_repository(
   name = "xla",
   path = xla_path,
)

load("@xla//:workspace3.bzl", "tf_workspace3")
tf_workspace3()

load("@xla//:workspace2.bzl", "tf_workspace2")
tf_workspace2(xla_path)

load("@xla//:workspace1.bzl", "tf_workspace1")
tf_workspace1()

load("@xla//:workspace0.bzl", "tf_workspace0")
tf_workspace0()
```

**Comment by hawkinsp** [comment]
I'm still not quite sure how this supposed to work. e.g., I have:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "xla",
    sha256 = "482f92c9bc3856d19a689b4170c80eaa7c26086ad2471047e753956d3855870c",
    strip_prefix = "xla-d9cfa4f71593cf5b178f1b4dbf0cf5fa794f7e58",
    urls = [
        "https://github.com/openxla/xla/archive/d9cfa4f71593cf5b178f1b4dbf0cf5fa794f7e58.tar.gz",
    ],
)

load("@xla//:workspace3.bzl", "xla_workspace3")
xla_workspace3()

load("@xla//:workspace2.bzl", "xla_workspace2")
xla_workspace2(xla_path)

load("@xla//:workspace1.bzl", "xla_workspace1")
xla_workspace1()

load("@xla//:workspace0.bzl", "xla_workspace0")
xla_workspace0()
```

There is no `xla_path` I can pass.

**Comment by GMNGeoffrey** [comment]
This should work: https://github.com/openxla/xla/commit/9517b9b8276ae92259327358b18d87b0d41d745f

**Comment by jakeharmon8** [comment]
Neither local or remote dependencies need `xla_path` anymore, so both should work now.

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "xla",
    sha256 = "35787a65d618f5f579eb05047489f1f9019a771a102f1dda0397b83137cce0f0",
    strip_prefix = "xla-3584da2aa364c925b52bbef4a56965650b506d19",
    urls = [
        "https://github.com/openxla/xla/archive/3584da2aa364c925b52bbef4a56965650b506d19.tar.gz",
    ],
)

load("@xla//:workspace3.bzl", "xla_workspace3")
xla_workspace3()

load("@xla//:workspace2.bzl", "xla_workspace2")
xla_workspace2()

load("@xla//:workspace1.bzl", "xla_workspace1")
xla_workspace1()

load("@xla//:workspace0.bzl", "xla_workspace0")
xla_workspace0()
```

**Comment by hawkinsp** [comment]
Ok, we're making progress.

Here's what I'm trying now.
* create a new directory.
* use your WORKSPACE above.
* `touch BUILD` to make an empty BUILD file
* `bazel build @xla//xla/python:xla_extension --experimental_repo_remote_exec`

The first problem I hit is:
```
ERROR: /usr/local/google/home/phawkins/.cache/bazel/_bazel_phawkins/34f30c3c86471580e2a24125a8dde2d6/external/xla/xla/python/BUILD:344:11: no such package '@dlpack//': The repository '@dlpack' could not be resolved: Repository '@dlpack' is not defined and referenced by '@xla//xla/python:dlpack'
```

It seems `@dlpack` is missing from the workspace files, but `xla/python` uses it. This is easy enough to work around: just copy `third_party/dlpack` from TF and add it to the XLA workspace.


If I work around that and try again, I hit: 
```
ERROR: /usr/local/google/home/phawkins/.cache/bazel/_bazel_phawkins/34f30c3c86471580e2a24125a8dde2d6/external/tsl/tsl/framework/contraction/BUILD:65:11: @tsl//tsl/framework/contraction:eigen_contraction_kernel_with_mkl depends on @mkl_dnn_v1//:mkl_dnn in repository @mkl_dnn_v1 which failed to fetch. no such package '@mkl_dnn_v1//': Unable to load package for //third_party/mkl_dnn:mkldnn_v1.BUILD: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /usr/local/google/home/phawkins/p/t/third_party/mkl_dnn
```

This looks like some sort of TSL workspace problem. The TSL workspace macros should define `mkl_dnn_v1`, but it's not being called. Maybe the easiest thing to do is clone that into the XLA repo as well?

Either way, I need `xla/python:xla_extension` to build in a submodule.

**Comment by jakeharmon8** [comment]
That took me longer to fix than I would've liked, but that target should be working now.

**Comment by hawkinsp** [comment]
Your turn again:

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "xla",
    sha256 = "2d812536b976cf6b2eda1109a4fe32255e2a7dcfad99fac500f3157905c8a55a",
    strip_prefix = "xla-6579738c83b4b5df8c5ee2f95b9b1f631ecbbf6d",
    urls = [
        "https://github.com/openxla/xla/archive/6579738c83b4b5df8c5ee2f95b9b1f631ecbbf6d.tar.gz",
    ],
)

load("@xla//:workspace3.bzl", "xla_workspace3")
xla_workspace3()

load("@xla//:workspace2.bzl", "xla_workspace2")
xla_workspace2()

load("@xla//:workspace1.bzl", "xla_workspace1")
xla_workspace1()

load("@xla//:workspace0.bzl", "xla_workspace0")
xla_workspace0()
```

```
$ bazel build @xla//xla/python:xla_extension --experimental_repo_remote_exec
Starting local Bazel server and connecting to it...
ERROR: Failed to load Starlark extension '@tsl//:workspace3.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @tsl
This could either mean you have to add the '@tsl' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
```

**Comment by jakeharmon8** [comment]
Ah, sorry, there's a `workspace4.bzl` now.

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "xla",
    sha256 = "2d812536b976cf6b2eda1109a4fe32255e2a7dcfad99fac500f3157905c8a55a",
    strip_prefix = "xla-6579738c83b4b5df8c5ee2f95b9b1f631ecbbf6d",
    urls = [
        "https://github.com/openxla/xla/archive/6579738c83b4b5df8c5ee2f95b9b1f631ecbbf6d.tar.gz",
    ],
)

load("@xla//:workspace4.bzl", "xla_workspace4")
xla_workspace4()

load("@xla//:workspace3.bzl", "xla_workspace3")
xla_workspace3()

load("@xla//:workspace2.bzl", "xla_workspace2")
xla_workspace2()

load("@xla//:workspace1.bzl", "xla_workspace1")
xla_workspace1()

load("@xla//:workspace0.bzl", "xla_workspace0")
xla_workspace0()

```

**Comment by hawkinsp** [comment]
Next roadblock: looks like there are visibility problems:

```
$ bazel build @xla//xla/python:xla_extension --experimental_repo_remote_exec
Loading:
Loading: 0 packages loaded
Analyzing: target @xla//xla/python:xla_extension (0 packages loaded, 0 targets configured)
ERROR: /usr/local/google/home/phawkins/.cache/bazel/_bazel_phawkins/34f30c3c86471580e2a24125a8dde2d6/external/tsl/tsl/platform/BUILD:1011:11: in cc_library rule @tsl//tsl/platform:bfloat16: alias '@eigen_archive//:eigen3' referring to target '@xla//third_party/eigen3:eigen3' is not visible from target '@tsl//tsl/platform:bfloat16'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /usr/local/google/home/phawkins/.cache/bazel/_bazel_phawkins/34f30c3c86471580e2a24125a8dde2d6/external/tsl/tsl/platform/BUILD:1011:11: Analysis of target '@tsl//tsl/platform:bfloat16' failed
ERROR: Analysis of target '@xla//xla/python:xla_extension' failed; build aborted:
INFO: Elapsed time: 0.341s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 2 targets configured)
```

There's also quite a bit of debug spew about duplicate repositories.

**Comment by jakeharmon8** [comment]
> Next roadblock: looks like there are visibility problems:

We only support building with `--nocheck_visibility` right now.

> There's also quite a bit of debug spew about duplicate repositories.

I'm already working on that one - should be fixed soon.

**Comment by hawkinsp** [comment]
One additional thing I noticed: some of the external dependencies (e.g., NCCL) have fallen behind their versions in the TF repo. We need to update at least NCCL to 2.16.5, and probably anything else that is older than its TF version.

**Comment by jakeharmon8** [comment]
That's related to the duplicate repositories. Currently, each `third_party` dependency has a version in TSL, XLA, and/or TF. I'm changing it so that there will only be one reference to each of those dependencies, which means there will only be one version for each, and that versioning will be shared by TSL, XLA, and TF. I'll make sure they're all synced to the newest version when I do that, and then it shouldn't be possible for them to get out of sync again.

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/14475 makes JAX build with OpenXLA. The main blocker to merging it will be the outdated dependencies like NCCL.

**Comment by jakeharmon8** [comment]
Dependency versions are now synced (other than NCCL, the only library that was outdated was PNG).

**Comment by hawkinsp** [comment]
One more problem: I tried a GPU build, and the NCCL build rules refer to `org_tensorflow` when they probably should use the TSL path:

https://github.com/openxla/xla/blob/48bc36f01ac542e87112d97f0bb97ca9b21626de/third_party/nccl/build_defs.bzl.tpl#L364

**Comment by hawkinsp** [comment]
Also filed https://github.com/openxla/xla/issues/1323 about the need for `--nocheck_visibility`.
